### ISSUE TITLE
[compose] 本地开发时的 boot up 方案

### ISSUE THREAD

**Issue by captainblue2013** [mohism-framework/mohism#2]
在本地开发时，如何快捷启动项目需要的基础设施（db，cache），
以及如何快速的启动全部子服务
 
 - 在compose所在目录下，就启动全部服务
 - 在服务的目录里，就寻找上一级的compose，启动出了“本服务”外的其他自服务

### 启动方式待定

**Comment by pankey-hox** [comment]
随着 这个项目产品化（只做基座），这个衣袖没有意义了
